// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uytwojtdnzvctzuhhtdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5dHdvanRkbnp2Y3R6dWhodGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzY0NzEsImV4cCI6MjA2ODE1MjQ3MX0.1FRs_TdlYwi1-T27UAI4GlIL06c6p1Gqcp0T0PVv5IM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});